"""Cloud Workflows YAML validator and builder using Pydantic v2."""

from .models import (
    parse_workflow,
    to_yaml,
    expr,
    Workflow,
    SimpleWorkflow,
    SubworkflowsWorkflow,
    WorkflowDefinition,
    Step,
    AssignStep,
    CallStep,
    ReturnStep,
    RaiseStep,
    SwitchStep,
    SwitchCondition,
    ForStep,
    ForBody,
    ParallelStep,
    ParallelBody,
    Branch,
    TryStep,
    TryCallBody,
    TryStepsBody,
    ExceptBody,
    RetryConfig,
    BackoffConfig,
    NestedStepsStep,
)
from .builder import (
    StepBuilder,
    Workflow,
    Subworkflow,
    WorkflowBuilder,
    build,
)
from .steps import (
    StepBase,
    Assign,
    Call,
    # Preferred names (no trailing underscores)
    Returns,
    DoReturn,
    Raises,
    DoRaise,
    Loop,
    DoTry,
    Switch,
    Parallel,
    Steps,
    # Backward-compat names (trailing underscores)
    Return_,
    Raise_,
    For,
    Try_,
)
from .parser import (
    analyze_yaml,
    analyze_workflow,
    AnalysisResult,
)
from .expressions import (
    validate_expression,
    validate_all_expressions,
    extract_expression_strings,
    extract_variable_references,
    parse_expression_ast,
    parse_expression_recover,
    walk,
    ExpressionError,
    # AST node types
    Node,
    NumberLiteral,
    StringLiteral,
    BoolLiteral,
    NullLiteral,
    Identifier,
    UnaryOp,
    BinaryOp,
    MemberAccess,
    IndexAccess,
    FunctionCall,
    ListLiteral,
    MapEntry,
    MapLiteral,
    ErrorNode,
)
from .variables import (
    analyze_variables,
    VariableIssue,
    Severity,
)

__all__ = [
    # Parsing
    "parse_workflow",
    "Workflow",
    "SimpleWorkflow",
    "SubworkflowsWorkflow",
    # Builders (preferred)
    "StepBuilder",
    "Workflow",
    "Subworkflow",
    "build",
    # Builder (backward-compat)
    "WorkflowBuilder",
    # Step sub-builders (preferred names first)
    "StepBase",
    "Assign",
    "Call",
    "Returns",
    "DoReturn",
    "Raises",
    "DoRaise",
    "Switch",
    "Loop",
    "Parallel",
    "DoTry",
    "Steps",
    # Step sub-builders (backward-compat names)
    "Return_",
    "Raise_",
    "For",
    "Try_",
    # Serialization
    "to_yaml",
    "expr",
    # Full analysis pipeline
    "analyze_yaml",
    "analyze_workflow",
    "AnalysisResult",
    # Expression validation
    "validate_expression",
    "validate_all_expressions",
    "extract_expression_strings",
    "extract_variable_references",
    "parse_expression_ast",
    "parse_expression_recover",
    "walk",
    "ExpressionError",
    # AST node types
    "Node",
    "NumberLiteral",
    "StringLiteral",
    "BoolLiteral",
    "NullLiteral",
    "Identifier",
    "UnaryOp",
    "BinaryOp",
    "MemberAccess",
    "IndexAccess",
    "FunctionCall",
    "ListLiteral",
    "MapEntry",
    "MapLiteral",
    "ErrorNode",
    # Variable analysis
    "analyze_variables",
    "VariableIssue",
    "Severity",
    # Model types (for direct construction / passthrough)
    "WorkflowDefinition",
    "Step",
    "AssignStep",
    "CallStep",
    "ReturnStep",
    "RaiseStep",
    "SwitchStep",
    "SwitchCondition",
    "ForStep",
    "ForBody",
    "ParallelStep",
    "ParallelBody",
    "Branch",
    "TryStep",
    "TryCallBody",
    "TryStepsBody",
    "ExceptBody",
    "RetryConfig",
    "BackoffConfig",
    "NestedStepsStep",
]
